### ISSUE TITLE
Epic: LMS MVP

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#2]
### Unauthenticated User

- [x] View a markdown file rendered with a consistent and accessible theme

- [x] Traverse content using helpful and accessible navigation menus
- [x] Bookmark or share any heading element on any markdown page
- [x] Listen to any markdown file using Speech Synthesis
- [x] Access iframes with remote content
- [x] View accessible images, SVGs, audio or movie files
- [x] Search through prerequisite content

### Git Authenticated User

- [x] Install the Mollify package as a dependency

- [x] Run a live preview environment locally to preview content during changes
- [x] Build a static bundle to be used as a public preview
- [x] ~~Install another LMS-enabled content repository as a submodule child~~
