### ISSUE TITLE
Epic: LMS Next

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#3]
- [ ] U may view an estimated reading time for a given markdown file
- [ ] U may export a given file or folder as PDF
- [ ] U may feedback on a given tag in a given markdown file
- [ ] U may save a given snippet as a favourite
