### ISSUE TITLE
Epic: CLI MVP

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#4]
The primary purpose of the CLI MVP is to provide an interface for creating, editing and removing markdown files according to the Mollify WOD.

- [x] G may create a given entity with metadata
- [x] G may remove a given entity or entities
- [x] G may migrate a given markdown file or files
- [ ] G may link a given submodule as a content child
