### ISSUE TITLE
Epic: CLI Next

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#5]
- [ ] G may stage files in git
- [ ] G may commit files in git
- [ ] G may push branches in git
- [ ] G may remove files in git
- [ ] G may initiate a content review
