### ISSUE TITLE
Epic: Flow MVP

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#6]
The purpose of the Flow MVP is to empower non-technical users with the power of Git version control through a narrow and opinionated flow.

- [x] User can preview changes to a markdown file
- [x] User can preview callout syntax in WYSIWYG
- [x] User can view a static diff diagram
