### ISSUE TITLE
Epic: Molly MVP

### ISSUE THREAD

**Issue by Fermain** [Fermain/-mollify#8]
- [ ] Molly offers helpful advice during the content creation process
- [ ] Molly offers helpful advice during the content review process
- [ ] Molly may access the CLI
- [x] Molly may access markdown content within the repository
- [x] Molly may discuss course content with student users
- [ ] Molly may speak using Speech Synthesis
- [x] Molly generates content summaries or outlines based on the existing course material
- [x] Molly provides keyword suggestions for better search
- [ ] Molly identifies and suggests relevant external resources to supplement course material
- [ ] Molly evaluates content readability and offers suggestions to improve clarity and conciseness
- [x] Molly generates quiz or assessment questions based on the course material
- [ ] Molly performs sentiment analysis on student feedback to identify areas for improvement
- [ ] Molly automatically generates course or lesson transcripts and captions for accessibility
- [x] Molly assists in identifying and filling content gaps within the course material
- [x] Molly provides personalised learning recommendations for students based on their progress and preferences

**Comment by Jenfer93** [comment]
I've started testing Molly on a few of these, I will provide a list under to let you know what has been tested. This is just by "talking" to her in the chat, and providing here with content directly there, as I have not yet been able to implement here in the lms package and don't have access to course content in md files. 

- [ ] Can provide keyword suggestions to better searching 
- [ ] Can provide suggestions to better the course material
- [ ] Can assist in identifying and filling content gaps withing course material
- [ ] Can create a quiz based on the content I provided, and the suggestions she added. (don't know how good the quiz is) 

(this will continue)

**Comment by Jenfer93** [comment]
As off 24.05, there has been an issue to the response from Molly, and we will have to check if this is a front end problem or a back end problem. So checking what Molly can do have to wait a little. 

Also want to report that we have to work on allowing Molly to read what is in the content on the pages, so that students can ask direct questions regarding the content on the page they are onn.

**Comment by Fermain** [comment]
This issue was resolved with some temporary code. This will need more attention in future, especially research on Streaming Responses and Event Sources. Molly works well for a student, next steps involve integrating this into the CLI and content creation process.

**Comment by Fermain** [comment]
This was a radically ambitious MVP in retrospect. Well done @Jenfer93 for your achievements here. Closing as done.
